---
- name: Get global_owner_public_key by jq from {{ ops_mgr_api_tmp_path }}/{{ ops_mgr_global_api_key_json }}
  shell: cat {{ ops_mgr_api_tmp_path }}/{{ ops_mgr_global_api_key_json }} | jq '.global_api_keys.global_owner_api_key.public_key' | tr -d '"'
  register: global_owner_public_key_result

- name: Get global_owner_private_key by jq from {{ ops_mgr_api_tmp_path }}/{{ ops_mgr_global_api_key_json }}
  shell: cat {{ ops_mgr_api_tmp_path }}/{{ ops_mgr_global_api_key_json }} | jq '.global_api_keys.global_owner_api_key.private_key' | tr -d '"'
  register: global_owner_private_key_result

- name: Define global_owner_public_key, global_owner_private_key
  set_fact:
    global_owner_public_key: "{{ global_owner_public_key_result.stdout }}"
    global_owner_private_key: "{{ global_owner_private_key_result.stdout }}"

- name: Print global_owner_public_key, global_owner_private_key which are read from {{ ops_mgr_api_tmp_path }}/{{ ops_mgr_global_api_key_json }}
  debug:
    msg: "global_owner_public_key={{ global_owner_public_key }}, global_owner_private_key={{ global_owner_private_key }}"

## Reminder: The new added user will receive an invitation to the organization or project when login Ops Mgr GUI, and should click [Accept] button
- name: Create One Organization/Project User
  uri:
    url: "{{ ops_mgr_api_endpoint_users }}"
    user: "{{ global_owner_public_key }}"
    password: "{{ global_owner_private_key }}"
    method: POST
    headers:
      Accept: "application/json"
      Content-Type: "application/json"
    body_format: json
    body: |
      {
        "username": "{{ users_param_username }}",
        "password": "{{ users_param_password }}",
        "firstName": "{{ users_param_firstName }}",
        "lastName": "{{ users_param_lastName }}",
        "emailAddress": "{{ users_param_emailAddress }}",
        "roles": [
          {
            "orgId" : "{{ grant_new_added_user_to_org_id }}",
            "roleName" : "{{ grant_new_added_user_to_org_roleName }}"
          },
          {
            "groupId": "{{ grant_new_added_user_to_project_id }}",
            "roleName": "{{ grant_new_added_user_to_project_roleName }}"
          }
        ]
      }
    status_code: [201, 409]
    validate_certs: false
  register: create_one_ops_mgr_user_response

- name: Print create_one_ops_mgr_user_response
  debug:
    msg: "{{ create_one_ops_mgr_user_response.json }}"