---
- name: Check if the source file exists
  stat:
    path: "{{ binary_path }}{{ package_name }}"
  register: source_file_stat

- name: Copy MongoDB binary to the target directory
  copy:
    src: "{{ binary_path }}{{ package_name }}"
    dest: /opt/mongodb/mms/mongodb-releases/
    owner: mongodb-mms
    group: mongodb-mms
    mode: '0644'
    remote_src: true
  register: copy_result
  changed_when: copy_result.changed
  when: source_file_stat.stat.exists

- name: Display copy result
  debug:
    msg: "Copy result: {{ copy_result }}"
  when: source_file_stat.stat.exists


- name: Check if the destination file exists
  stat:
    path: "/opt/mongodb/mms/mongodb-releases/{{ package_name }}"
  register: destination_file_stat


- name: Display destination file existence
  debug:
    msg: "Destination file  /opt/mongodb/mms/mongodb-releases/{{ package_name }} exists: {{ destination_file_stat.stat.exists }}"

- name: fail if Display destination file does not exist
  fail:
    msg: "Failed to find the destination file /opt/mongodb/mms/mongodb-releases/{{ package_name }}"
  when: not destination_file_stat.stat.exists
