---
- name: Generate encrypted username/password
  shell: |
    set timeout 10
    spawn /opt/mongodb/mms/bin/credentialstool --username mms --password
    expect "Enter Password:"
    send "{{ mms_admin_pwd }}\r"
    expect eof
    exit 0
  args:
    executable: /usr/bin/expect
  register: encrypted_result

- name: Print encrypted_result.stdout_lines
  debug:
    msg: '{{ encrypted_result.stdout_lines }}'

- name: Extract encrypted username/password
  set_fact:
    encrypted_username: "{{ encrypted_result.stdout | regex_search('\r\nUsername: (.*)') | regex_replace('\r\nUsername: (.*)', '\\1') | trim }}"
    encrypted_password: "{{ encrypted_result.stdout | regex_search('\r\nPassword: (.*)') | regex_replace('\r\nPassword: (.*)', '\\1') | trim }}"

- name: Print encrypted username and password
  debug:
    msg:
      - "{{ encrypted_username }}"
      - "{{ encrypted_password }}"