---
- name: Restart the first mongodb-mms.service
  systemd:
    name: mongodb-mms
    state: restarted
    enabled: true
  ignore_errors: true

- name: Wait for the port {{ mms_conf_base_ssl_port }} to be accessible for mongodb-mms.service
  wait_for:
    port: "{{ mms_conf_base_ssl_port }}"
    host: "{{ inventory_hostname }}"
    timeout: 300
  register: restart_mms_result

- name: Print restart_mms_result
  debug:
    msg: "{{ restart_mms_result }}"

- name: Copy {{ mms_gen_key_path }}{{ mms_gen_key_file }} to {{ tmp_mongodb_scp }} directory
  copy:
    src: "{{ mms_gen_key_path }}{{ mms_gen_key_file }}"
    dest: "{{ tmp_mongodb_scp }}/{{ mms_gen_key_file }}"
    remote_src: true
    mode: '0777'
    owner: mongodb-mms
    group: mongodb-mms