---
- name: Wait for 30 seconds to ensure mongod is running
  pause:
    seconds: 30

- name: Check if AppDB is running
  systemd:
    name: mongod
    state: started
  register: mongod_status

- name: Display AppDB status
  debug:
    msg: "Mongod status is : {{ mongod_status.status.ActiveState }} and state time was : {{ mongod_status.status.ExecMainStartTimestamp }}"
