---
- name: Modify mongod.service configuration file
  lineinfile:
    path: /usr/lib/systemd/system/mongod.service
    regexp: '^Environment="OPTIONS=-f /etc/mongod.conf"'
    line: 'Environment="OPTIONS=-f /data/appdb/mongod.conf"'
    state: present
  register: mongod_service_update

- name: Confirm if modification occurred
  debug:
    msg: "The Mongod service configuration file has been updated."
  when: mongod_service_update.changed

- name: Reload systemd manager configuration
  systemd:
    daemon_reload: yes
  when: mongod_service_update.changed