# tasks/stop_db.yml
---
- name: Stop AppDB
  systemd:
    name: mongod
    state: stopped
  register: stop_appdb_result

- name: Display the stop AppDB result
  debug:
    msg: "Stop result: {{ stop_appdb_result.status }}"