---
- import_tasks: clear_history_json.yml
  tags: clear_history_json
  when: inventory_hostname == groups['sharded-cluster-mongos'][0]

- import_tasks: install_jq.yml
  tags: install_jq

- import_tasks: prepare_cluster_dir.yml
  tags: prepare_cluster_dir

- import_tasks: config_mdb_clusters_tls.yml
  tags: config_mdb_clusters_tls
  when: inventory_hostname == groups['sharded-cluster-mongos'][0]

- import_tasks: config_mdb_clusters_authenticate.yml
  tags: config_mdb_clusters_authenticate
  when: inventory_hostname == groups['sharded-cluster-mongos'][0]

- import_tasks: config_mdb_agent_authenticate.yml
  tags: config_mdb_agent_authenticate
  when: inventory_hostname == groups['sharded-cluster-mongos'][0]

- import_tasks: config_mdb_agent_tls.yml
  tags: config_mdb_agent_tls
  when: inventory_hostname == groups['sharded-cluster-mongos'][0]

- import_tasks: create_first_automation_key_file.yml
  tags: create_first_automation_key_file
  when: inventory_hostname == groups['sharded-cluster-mongos'][0]

- import_tasks: create_others_automation_key_file.yml
  tags: create_others_automation_key_file
  when: inventory_hostname != groups['sharded-cluster-mongos'][0]

- import_tasks: create_automation_internal_user.yml
  tags: create_automation_internal_user
  when: inventory_hostname == groups['sharded-cluster-mongos'][0]

- import_tasks: create_cluster_user.yml
  tags: create_cluster_user
  when: inventory_hostname == groups['sharded-cluster-mongos'][0]

- import_tasks: create_processes_json.yml
  tags: create_processes_json

- import_tasks: scp_processes_json.yml
  tags: scp_processes_json

- import_tasks: create_replicaSets_members_json.yml
  tags: create_replicaSets_members_json

- import_tasks: scp_replicaSets_members_json.yml
  tags: scp_replicaSets_members_json

- import_tasks: create_replicaSets_json.yml
  tags: create_replicaSets_json
  when: inventory_hostname == groups['sharded-cluster-mongos'][0]

- import_tasks: create_sharding_json.yml
  tags: create_sharding_json
  when: inventory_hostname == groups['sharded-cluster-mongos'][0]

- import_tasks: create_project_roles_json.yml
  tags: create_project_roles_json
  when: inventory_hostname == groups['sharded-cluster-mongos'][0]

- import_tasks: deploy_cluster.yml
  tags: deploy_cluster
  when: inventory_hostname == groups['sharded-cluster-mongos'][0]

- import_tasks: create_soft_link_mongod_conf.yml
  tags: create_soft_link_mongod_conf
  when: inventory_hostname not in groups['sharded-cluster-mongos']