---
- name: Merge the root CA and intermediate CA into a single PEM file
  become: true
  shell:
    cat {{ ca_cert_remote_dest }}{{ intermediate_cert_name }} {{ ca_cert_remote_dest }}{{ root_cert_name }}> {{ ca_cert_remote_dest }}{{ ca_cert_remote_name }}
  args:
    chdir: '{{ ca_cert_remote_dest }}'
  register: merge_result
  changed_when: false

- name: Display merge result
  debug:
    msg: "Merged private key and signed cert: {{ merge_result }}"