---
- name: Change owner to mongodb-mms if the node is Ops Manager
  become: true
  file:
    path: '{{ ca_cert_installation_path }}{{ ca_cert_remote_name }}'
    owner: '{{ ops_ca_cert_remote_owner }}'
    group: '{{ ops_ca_cert_remote_group }}'
  register: chown_result
  changed_when: chown_result.changed

- name: Display change owner result
  debug:
    msg: "Changed owner to mongodb-mms: {{ chown_result }}"