---
- name: Define hostname_list
  set_fact:
    hostname_list: "{{ groups['ops-mgr-appdb'] | map('extract', hostvars, 'ansible_fqdn') | list | unique}}"

- name: Print hostname_list
  debug:
    var: hostname_list