---
- name: Check if MongoDB RPM package is installed
  command:
    cmd: rpm -q {{ mdb_server_pkg }}
  register: result_check_pkg
  ignore_errors: true
  failed_when: false
  changed_when: false

- name: Install MongoDB RPM package
  command:
    cmd: rpm -Uvh '{{ install_binary_path }}/{{ mdb_server_pkg }}-{{ mdb_server_version }}.rpm'
  register: result_install_pkg
  when:
    - result_check_pkg is defined
    - result_check_pkg.rc != 0

- name: Check MongoDB RPM package installation result (Success)
  debug:
    msg: "Success: Install MongoDB RPM package"
  when:
    - result_install_pkg.rc is defined
    - result_install_pkg.rc == 0

- name: Check MongoDB RPM package installation result (Failed)
  debug:
    msg: "Failed: Install MongoDB RPM package"
  when:
    - result_install_pkg.rc is defined
    - result_install_pkg.rc != 0