---
- name: Restart mongod.service
  systemd:
    name: mongod
    state: restarted
    enabled: true
  ignore_errors: true

- name: Wait for the port {{ appdb_port }} to be accessible for mongod.service
  wait_for:
    port: "{{ appdb_port }}"
    host: "{{ inventory_hostname }}"
    timeout: 300
  register: restart_mongod_result

- name: Print restart_mongod_result
  debug:
    msg: "{{ restart_mongod_result }}"