---
- name: Get the Automation Configuration for Deploying Blockstore Cluster
  uri:
    url: "{{ ops_mgr_api_endpoint_automationConfig }}"
    user: "{{ project_api_public_key }}"
    password: "{{ project_api_private_key }}"
    method: GET
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
    status_code: 200
    validate_certs: false
  register: get_automation_configuration_response

- name: Print get_automation_configuration_response
  debug:
    var: get_automation_configuration_response

- name: Define current_automation_config_json
  set_fact:
    current_automation_config_json: "{{ get_automation_configuration_response.json }}"

- name: Print current_automation_config_json
  debug:
    var: current_automation_config_json

- name: Write into the file {{ ops_mgr_api_current_automation_config }}
  copy:
    content: "{{ current_automation_config_json }}"
    dest: "{{ ops_mgr_api_current_automation_config }}"
    mode: '0755'
    owner: root
    group: root
  register: write_current_config_result

- name: Print write_current_config_result
  debug:
    var: write_current_config_result

- name: Upsert replicaSets to the {{ ops_mgr_api_current_automation_config }} by jq
  shell: |
    jq --argfile merged_replicaSets {{ ops_mgr_api_tmp_path }}/{{ jq_merged_replicaSets }} \
    'del(.replicaSets[] | select(._id == "{{ args2_6_replication_replSetName }}")) | .replicaSets += [$merged_replicaSets]' {{ ops_mgr_api_current_automation_config }} \
    > {{ ops_mgr_api_updated_automation_config }}
  register: upsert_replicaSets_result

- name: Print upsert_replicaSets_result
  debug:
    var: upsert_replicaSets_result

- name: Upsert processes to the {{ ops_mgr_api_current_automation_config }} by jq
  shell: |
    jq --argfile processes_{{ index + 1 }} {{ ops_mgr_api_tmp_path }}/processes_{{ index + 1 }}.json 'del(.processes[] | select(.name == "{{ args2_6_replication_replSetName }}_{{ index + 1 }}")) | .processes += [$processes_{{ index + 1 }}]' {{ ops_mgr_api_updated_automation_config }} \
    > {{ ops_mgr_api_temp_automation_config }} \
    && mv {{ ops_mgr_api_temp_automation_config }} {{ ops_mgr_api_updated_automation_config }}
  register: upsert_processes_result
  loop: "{{ play_hosts }}"
  loop_control:
    index_var: index

- name: Print upsert_processes_result
  debug:
    var: upsert_processes_result

- name: Read file from remote node into updated_automation_config
  slurp:
    src: "{{ ops_mgr_api_updated_automation_config }}"
  register: updated_automation_config

- name: Print updated_automation_config
  debug:
    msg: "{{ updated_automation_config.content | b64decode }}"

- name: Define updated_automation_config_json
  set_fact:
    updated_automation_config_json: "{{ updated_automation_config.content | b64decode }}"

- name: Print updated_automation_config_json
  debug:
    var: updated_automation_config_json

- name: Update the Automation Configuration for Deploying Blockstore Cluster
  uri:
    url: "{{ ops_mgr_api_endpoint_automationConfig }}"
    user: "{{ project_api_public_key }}"
    password: "{{ project_api_private_key }}"
    method: PUT
    headers:
      Accept: "application/json"
      Content-Type: "application/json"
    body: "{{ updated_automation_config_json | to_json }}"
    status_code: 200
    validate_certs: false
  register: update_automation_configuration_response

- name: Print update_automation_configuration_response
  debug:
    var: update_automation_configuration_response