---
- name: Populate service facts
  service_facts:

- name: Print mongod and mongodb-mms service facts
  debug:
    msg:
      - "Mongodb-mms service: {{ ansible_facts.services['mongodb-mms.service'] }}"
      - "Mongodb-mms: {{ ansible_facts.services['mongodb-mms'] }}"
  ignore_errors: yes