---
- name: DataNode DB Mongosh connectivity check
  command:
    cmd: "mongosh --host {{ ansible_fqdn }} --port {{ data_db_port }} -u {{data_dbadmin_user}} --tls --tlsCAFile {{ ca_cert_path }} --authenticationDatabase '$external' --authenticationMechanism 'GSSAPI' --eval '{{ validation_command }}'"
  register: data_node_check
  changed_when: False


- name: Display DataNode connectivity check result
  debug:
    msg: "DataNode DB connectivity check result: {{ data_node_check.stdout }}"


- name: Verify DataNode is running
  fail:
    msg: "DataNode health check failed. Unable to connect or ping the database."
  when: data_node_check.rc != 0

- name: DataNode Version check
  command:
    cmd: "mongosh --host {{ ansible_fqdn }} --port {{ data_db_port }} -u {{data_dbadmin_user}} --tls --tlsCAFile {{ ca_cert_path }} --authenticationDatabase '$external' --authenticationMechanism 'GSSAPI' --eval 'db.version()'"
  register: data_node_version_check
  changed_when: False

- name: Display DataNode version check result
  debug:
    msg: "AppDB version check result: {{ data_node_version_check.stdout }}"
