---
- import_tasks: ops_manager_node_mongosh_connectivity.yml
  tags: ops_manager_node_mongosh_connectivity
  when: "'ops-mgr-appdb' in group_names"

- import_tasks: ops_manager_blockstore_mongosh_connectivity.yml
  tags: ops_manager_blockstore_mongosh_connectivity
  when: "'ops-mgr-blockstore' in group_names"

- import_tasks: ops_manager_app_health_check.yml
  tags: ops_manager_health_check
  when: "'ops-mgr-application' in group_names"

- import_tasks: ops_manager_agent_check.yml
  tags: ops_manager_agent_check

- import_tasks: data_node_mongosh_connectivity.yml
  tags: data_node_mongosh_connectivity
  when: "'DATA_NODES' in group_names"



