# tasks/restart_agent.yml
---
- name: Restart Ops Manager Agent
  systemd:
    name: mongodb-mms-automation-agent
    state: restarted
  register: restart_result
  changed_when: restart_result.changed == True

- name: Display mongodb-mms-automation-agent restart result
  debug:
    msg: "restart result: {{ restart_result }}"

- name: Wait for 30 seconds to ensure mongodb-mms-automation-agent is running
  pause:
    seconds: 30

- name: Check if mongodb-mms-automation-agent is running
  systemd:
    name: mongodb-mms-automation-agent
    state: started
  register: agent_status

- name: Display mongodb-mms-automation-agent status
  debug:
    msg: "mongodb-mms status is : {{ agent_status.status.ActiveState }} and state time was : {{ agent_status.status.ExecMainStartTimestamp }}"