# tasks/upgrade_agent.yml
---
- name: Download Ops Manager Agent RPM
  get_url:
    url: "{{ ops_manager_host }}/download/agent/automation/{{ ops_manager_agent_name }}"
    dest: "{{ binary_path }}"
    validate_certs: false
    mode: "0644"

- name: Check current installation
  command:
    cmd: zypper search -i -s mongodb-mms-automation-agent-manager
  register: check_result
  changed_when: false

- name: Display the check result
  debug:
    msg: "Check result: {{ check_result.stdout }}"

- name: Install Ops Manager Agent RPM
  zypper:
#    name: "{{ package_info[version]['packages_list'] |map('regex_replace', '^(.+)$', '%s/\\1' % binary_path) |list }}"
    name: '{{ binary_path }}{{ ops_manager_agent_name }}'
    disable_gpg_check: yes
    state: present
  register: install_result

- name: Display the install result
  debug:
    msg: "Install result: {{ install_result }}"

- name: Check current installation
  command:
    cmd: zypper search -i -s mongodb-mms-automation-agent-manager
  register: check_result
  changed_when: false

- name: Display the check result
  debug:
    msg: "Check result: {{ check_result.stdout }}"